// frontend/src/App.jsx
import React, { useState } from "react";

export default function App() {
  const titel = "Mensabot Testseite";

  const [userInput, setUserInput] = useState("");
  const [backendResponse, setBackendResponse] = useState("");
  const [isSending, setIsSending] = useState(false);

  const sendMessage = async () => {
    if (!userInput.trim()) return;

    setIsSending(true);
    const textToSend = userInput;

    try {
      const response = await fetch("/api/chat", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ message: textToSend }),
      });

      const data = await response.json();
      setBackendResponse(data.reply || "Keine Antwort vom Backend erhalten.");
    } catch (error) {
      console.error("Fehler beim Senden:", error);
      setBackendResponse("Fehler beim Verbinden mit dem Backend.");
    } finally {
      setUserInput("");
      setIsSending(false);
    }
  };

  return (
    <div style={{ padding: "20px", fontFamily: "sans-serif" }}>
      <h1>{titel}</h1>

      <div>
        {backendResponse ? (
          <p>{backendResponse}</p>
        ) : (
          <p>Warte auf deine Eingabe...</p>
        )}
      </div>

      <div>
        <input
          type="text"
          value={userInput}
          onChange={(e) => setUserInput(e.target.value)}
          disabled={isSending}
          placeholder="Gib hier deinen Text ein..."
          style={{ marginRight: "10px" }}
        />
        <button
          onClick={sendMessage}
          disabled={!userInput.trim() || isSending}
        >
          {isSending ? "Sende..." : "Senden an Backend"}
        </button>
      </div>
    </div>
  );
}

// frontend/src/App.vue
<template>
    <h1>{{ titel }}</h1>
     <div>
        <p v-if="backendResponse">
            {{ backendResponse }}
        </p>
        <p v-else>
            Warte auf deine Eingabe...
        </p>
    </div>
    <div>
        <input
        type="text"
        v-model="userInput"
        :disabled="isSending"
        placeholder="Gib hier deinen Text ein..."
        />
        <button
        @click="sendMessage"
        :disabled="!userInput.trim() || isSending"
        >
        {{ isSending ? 'Sende...' : 'Senden an Backend' }}
        </button>
    </div>
</template>

<script setup>
    import { ref } from 'vue';
    const titel = 'Mensabot Testseite';

    const userInput = ref('');
    const backendResponse = ref('');
    const isSending = ref(false);

    async function sendMessage() {
        if (!userInput.value.trim()){
            return;
        }

        isSending.value = true;
        const textToSend = userInput.value;

        try{
            const response = await fetch('/api/chat', { 
                method: 'POST', 
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({ message: textToSend }) 
            });
            const data = await response.json();
            backendResponse.value = data.reply || 'Keine Antwort vom Backend erhalten.';

        } catch (error) {
            console.error('Fehler beim Senden:', error);
            backendResponse.value = 'Fehler beim Verbinden mit dem Backend.';
        } finally { //zurücksetzen
            userInput.value = ''; 
            isSending.value = false;
        }
    }
    
</script>
